name: Deb

on:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Theos & Tools
        run: |
          brew install ldid
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Build Package
        run: |
          export THEOS=~/theos
          if [ -d "ytkace-0.9.2" ]; then
            cd ytkace-0.9.2
          fi
          make clean
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AraDev-deb
          path: |
            packages/*.deb
            ytkace-0.9.2/packages/*.deb
